name: Build ROCK

on:
  workflow_call:
    secrets:
      SSH_PRIVATE_KEY:
        required: true

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ssh-key: ${{ secrets.SSH_PRIVATE_KEY }}
          submodules: recursive

      - name: Copy keys
        run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
          echo "${{ secrets.SSH_PUBLIC_KEY }}" > ~/.ssh/id_ed25519.pub

      - name: Set ssh
        uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Get SSH_AUTH_SOCK
        id: ssh
        run: echo "$SSH_AUTH_SOCK"

      - name: Fetch github keys
        id: keys
        run: ssh-keyscan -H github.com >> ~/.ssh/known_hosts

      - name: Get files
        id: files
        run: ls ~/.ssh

      - name: Get name
        id: name
        run: echo "name=$(yq '.name' rockcraft.yaml)" >> "$GITHUB_OUTPUT"

      - uses: canonical/craft-actions/rockcraft-pack@main
        id: rockcraft

      - name: Install Syft
        run: |
          curl -sSfL https://raw.githubusercontent.com/anchore/syft/main/install.sh | sh -s -- -b /usr/local/bin

      - name: Create SBOM
        run: syft ${{ steps.rockcraft.outputs.rock }} -o spdx-json=${{ steps.name.outputs.name }}.sbom.json

      - name: Upload SBOM
        uses: actions/upload-artifact@v3
        with:
          name: ${{ steps.name.outputs.name }}-sbom
          path: "${{ steps.name.outputs.name }}.sbom.json"

      - uses: actions/upload-artifact@v3
        with:
          name: rock
          path: ${{ steps.rockcraft.outputs.rock }}
