name: Push Changes

on:
  push:
    branches-ignore:
      - "main"
    paths:
      - "rockcraft.yaml"
      - ".github/workflows/**.yaml"

jobs:
  build:
    uses: ./.github/workflows/build.yaml
    secrets:
      SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
